version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: support_case_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: support_case_backend
    depends_on:
      - mysql
    ports:
      - "3001:3001"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./src/backend/server:/usr/src/app/server
      - /usr/src/app/server/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: support_case_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}

volumes:
  db_data:

