FROM node:18-alpine AS builder
WORKDIR /usr/src/app
COPY src/backend/package.json        ./package.json
COPY src/backend/package-lock.json   ./package-lock.json
RUN npm install
COPY src/backend/server/ ./server
EXPOSE 3001
CMD ["node", "server/server.js"]

